In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
dataset = pd.read_csv('data_no_na.csv',sep=',',encoding="utf-8")

In [ ]:
dataset['opened']=pd.to_datetime(dataset['opened'])
dataset['closed']=pd.to_datetime(dataset['closed'])
dataset['difference'] = [(dataset['opened'][i] - dataset['closed'][i]) for i in range(len(dataset['opened']))]

In [ ]:
dataset['difference_mins'] = [int(dataset['difference'][i].total_seconds()/60) for i in range(len(dataset['difference']))]

In [ ]:
dataset['difference_mins']

0          -577
1           -20
2          -424
3        -10530
4          -346
          ...
452160     -507
452161    -2016
452162   -34703
452163     -575
452164      -10
Name: difference_mins, Length: 452165, dtype: int64

In [ ]:
dataset['difference_mins'] = abs(dataset['difference_mins'])

In [ ]:
dataset['difference_mins']

0           577
1            20
2           424
3         10530
4           346
          ...
452160      507
452161     2016
452162    34703
452163      575
452164       10
Name: difference_mins, Length: 452165, dtype: int64

In [ ]:
dataset.drop('time_mins',axis=1)

,Unnamed: 0,caseID,opened,closed,responsible_agency,category,sup_district,neighborhood,Latitude,Longitude,...,pop,households,median_hInc,percent_pov,eduHS,vehicles,num_business,num_facilities,difference,difference_mins
0,1,11884029,2020-01-01 00:07:00,2020-01-01 09:44:00,Recology_Abandoned,Street and Sidewalk Cleaning,8,Castro,37.764374,-122.430885,...,"68,200","34,190","$121,250",7%,9%,"36,910",19485,64,-1 days +14:23:00,577
1,2,11884069,2020-01-01 00:42:00,2020-01-01 01:02:00,Parking Enforcement Dispatch Queue,Parking Enforcement,5,Panhandle,37.776394,-122.440577,...,"84,030","40,460","$91,055",13%,14%,"33,550",20027,135,-1 days +23:40:00,20
2,3,11884079,2020-01-01 00:51:00,2020-01-01 07:55:00,Parking Enforcement Dispatch Queue,Parking Enforcement,1,Inner Richmond,37.776105,-122.463030,...,"79,970","32,240","$83,215",11%,22%,"38,790",13684,162,-1 days +16:56:00,424
3,4,11884088,2020-01-01 00:56:00,2020-01-08 08:26:00,DPW Ops Queue,Street and Sidewalk Cleaning,4,Outer Sunset,37.749508,-122.494255,...,"77,000","26,680","$88,801",10%,28%,"41,520",10562,60,-8 days +16:30:00,10530
4,5,11884100,2020-01-01 01:00:00,2020-01-01 06:46:00,Parking Enforcement Dispatch Queue,Parking Enforcement,10,Silver Terrace,37.737830,-122.398007,...,"75,250","23,910","$69,915",16%,42%,"34,520",20132,300,-1 days +18:14:00,346
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452160,464351,13315585,2020-12-31 22:46:00,2021-01-01 07:13:00,Parking Enforcement Dispatch Queue,Parking Enforcement,10,Potrero Hill,37.754272,-122.406188,...,"75,250","23,910","$69,915",16%,42%,"34,520",20132,300,-1 days +15:33:00,507
452161,464352,13315601,2020-12-31 23:04:00,2021-01-02 08:40:00,Recology_Overflowing,Street and Sidewalk Cleaning,6,Rincon Hill,37.787708,-122.391783,...,"69,360","37,280","$54,819",23%,29%,"18,410",40514,201,-2 days +14:24:00,2016
452162,464353,13315603,2020-12-31 23:07:00,2021-01-25 01:30:00,RPD TMA Queue,Rec and Park Requests,10,Bayview,37.738355,-122.383430,...,"75,250","23,910","$69,915",16%,42%,"34,520",20132,300,-25 days +21:37:00,34703
452163,464354,13315618,2020-12-31 23:22:00,2021-01-01 08:57:00,Recology_Abandoned,Street and Sidewalk Cleaning,9,Mission,37.762157,-122.414876,...,"86,430","30,580","$83,839",12%,35%,"35,380",18107,89,-1 days +14:25:00,575
452164,464355,13315627,2020-12-31 23:28:00,2020-12-31 23:38:00,Parking Enforcement Dispatch Queue,Parking Enforcement,8,Buena Vista,37.764178,-122.445009,...,"68,200","34,190","$121,250",7%,9%,"36,910",19485,64,-1 days +23:50:00,10

In [ ]:
dataset.to_csv(r'C:\Users\whych\Desktop\dataset_time_difference.csv',sep =',', index=False)

Personal Notes

In [ ]:
wrong_row = [i for i in range(len(dataset['difference_mins'])) if abs(dataset['difference_mins'][i]) != int(dataset['time_mins'][i])]

In [ ]:
wrong_row

NameError: ignored

In [ ]:
len(wrong_row)

208501

In [ ]:
dataset_time = dataset.drop(index = wrong_row)

In [ ]:
type(dataset_time)

pandas.core.frame.DataFrame

In [ ]:
dataset_time.head()

,Unnamed: 0,caseID,opened,closed,time_mins,responsible_agency,category,sup_district,neighborhood,Latitude,...,pop,households,median_hInc,percent_pov,eduHS,vehicles,num_business,num_facilities,difference,difference_mins
0,1,11884029,2020-01-01 00:07:00,2020-01-01 09:44:00,577,Recology_Abandoned,Street and Sidewalk Cleaning,8,Castro,37.764374,...,"68,200","34,190","$121,250",7%,9%,"36,910",19485,64,-1 days +14:23:00,-577
1,2,11884069,2020-01-01 00:42:00,2020-01-01 01:02:00,20,Parking Enforcement Dispatch Queue,Parking Enforcement,5,Panhandle,37.776394,...,"84,030","40,460","$91,055",13%,14%,"33,550",20027,135,-1 days +23:40:00,-20
2,3,11884079,2020-01-01 00:51:00,2020-01-01 07:55:00,424,Parking Enforcement Dispatch Queue,Parking Enforcement,1,Inner Richmond,37.776105,...,"79,970","32,240","$83,215",11%,22%,"38,790",13684,162,-1 days +16:56:00,-424
4,5,11884100,2020-01-01 01:00:00,2020-01-01 06:46:00,346,Parking Enforcement Dispatch Queue,Parking Enforcement,10,Silver Terrace,37.737830,...,"75,250","23,910","$69,915",16%,42%,"34,520",20132,300,-1 days +18:14:00,-346
5,6,11884116,2020-01-01 01:07:00,2020-01-02 00:33:00,1406,DPW Ops Queue,Street and Sidewalk Cleaning,3,Financial District,37.795876,...,"72,360","39,840","$59,111",17%,30%,"19,420",46060,161,-1 days +00:34:00,-1406

In [ ]:
dataset_time.to_csv(r'C:\Users\whych\Desktop\dataset_time.csv',sep =',', index=False)